parameters:
    widop_http_adapter.buzz.class: Widop\HttpAdapterBundle\Model\BuzzHttpAdapter
    widop_http_adapter.curl.class: Widop\httpAdapterBundle\Model\CurlHttpAdapter

services:
    widop_http_adapter.buzz:
        class: %widop_http_adapter.buzz.class%

    widop_http_adapter.curl:
        class: %widop_http_adapter.curl.class%
